### ISSUE TITLE
work with deadlock stacking boxes

### ISSUE THREAD

**Issue by draddy82** [DerMistkaefer/Factorio_Better-Belts#14]
[data-updates.zip](https://github.com/DerMistkaefer/Factorio_Better-Belts/files/6152408/data-updates.zip)
hi, 
i missed better belts to work with deadlock - so i just "updated" it via data-updates.lua 

`if deadlock then
	deadlock.add_tier({
		transport_belt      = "BetterBelts_ultra-transport-belt",
		colour              = {r=0,g=211,b=37},
		technology          = "logistics-3",
		order				= "d",
		loader				= "Ultra-CompactLoader", 		
		loader_ingredients  = {
			{"express-transport-belt-loader",1},
			{"iron-gear-wheel",40},
		},
		loader_recipe		= "Ultra-CompactLoader",
		loader_item			= "Ultra-CompactLoader",
		beltbox				= "Ultra-Beltbox",
		beltbox_ingredients = {
			{"express-transport-belt-beltbox",1},
			{"steel-plate",40},
			{"iron-gear-wheel",40},
			{"processing-unit",5},
		},
		beltbox_recipe		= "Ultra-Beltbox",
		beltbox_item 		= "Ultra-Beltbox",
		beltbox_technology  = "deadlock-stacking-3",
	})
	  
	if data.raw.furnace["BetterBelts_ultra-transport-belt-beltbox"] then
		data.raw.furnace["express-transport-belt-beltbox"].next_upgrade = "BetterBelts_ultra-transport-belt-beltbox"
	end
	if data.raw.loader["BetterBelts_ultra-transport-belt-beltbox"] then
		data.raw.loader["express-transport-belt-loader"].next_upgrade = "BetterBelts_ultra-transport-belt-loader"
	end
end`

this will add deadlocks mini loaders and the stackingbox for better belts, maybe you can / will add this in future ;)

**Comment by DerMistkaefer** [comment]
Hello @draddy82,
thanks for your contribution.

I have checked your code and implemented it into the mod. 

I have change the entity names of the deadlock beltbox and loader, add the localisation andd ad migration so your entitiies should be migraded.

Thanks again. Its released in 1.3.1 👍

**Comment by draddy82** [comment]
hi @DerMistkaefer 
sounds good - but ...

little mistake 
![grafik](https://user-images.githubusercontent.com/61713756/111539276-f9f99300-876d-11eb-9778-71b13d73f588.png)
this one is the box - it will stack the items 
and 
![grafik](https://user-images.githubusercontent.com/61713756/111539325-0d0c6300-876e-11eb-86b3-5b91c2303840.png)
this is the loader, it loads / deloads items to chests, stacking boxes and so on 

it work technical, but the names are switched over :)

so - 1.3.2? ;)

best regards
draddy

**Comment by DerMistkaefer** [comment]
Arg. Yes you right it stands corret there but i have mis named it. 🤦‍♂️ 🤣
![image](https://user-images.githubusercontent.com/15692249/111540415-69bc4d80-876f-11eb-94ee-321e0eb886f8.png)

I have fixed it. Thank you.
